title: David Castro-Pena # your name (or website title) here
logo: "/images/22_04-GFH_Headshots-9541.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 
  BA Industrial EngineerIng. MA Public Policy. University of California, San Diego 
  <br><br>
  Bridging evidence with effective policy and management solutions
  <br><br>
  <a href="https://www.linkedin.com/in/davidcastropena/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
