title: David Castro-Pena # your name (or website title) here
logo: "/images/circle.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 
  Industrial Engineer. Finance professional. MA. Public Policy/Econometrics. University of California, San Diego
  dcastrop@ucsd.edu
  MSc. Computational Social Science (Management Science and Engineering). Stanford University 
  <br><br>
  Solving 
  <br><br>
  <a href="https://www.linkedin.com/in/davidcastropena/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
